const ROUTE_HOME_PAGE = "/";
const ROUTE_APPLICATION_FORM = "/ApplicationForm"
const ROUTE_GEOLOCATION_FORM = "/GeoLocation"
const ROUTE_LOGIN_FORM = "/login"
const ROUTE_TICKETS = "/tickets"
const ROUTE_CHANGE_ORDERS = "/ChangeOrders"

export {ROUTE_HOME_PAGE,ROUTE_APPLICATION_FORM,ROUTE_GEOLOCATION_FORM,ROUTE_LOGIN_FORM, ROUTE_TICKETS,ROUTE_CHANGE_ORDERS};